### ISSUE TITLE
Template fails on Redis install

### ISSUE THREAD

**Issue by fyaconiello** [platformsh-templates/laravel#9]
I noticed 2 issues which may be related.

- Installing the Laravel template using the platform.sh wizard fails - an empty repo is created
- When I manually copy the example from this repo and attempt to push it to platform.sh, I get a failure on redis install:
```
Total 198 (delta 35), reused 0 (delta 0), pack-reused 0

Validating submodules

Validating configuration files

E: Error parsing configuration files:
    - applications: The "redis" extension is not supported for php:7.4
        <unknown>
To git.us-2.platform.sh:h4fgy55i6fzrq.git
 ! [remote rejected] master -> master (invalid configuration files)
error: failed to push some refs to 'h4fgy55i6fzrq@git.us-2.platform.sh:h4fgy55i6fzrq.git'
```

**Comment by fyaconiello** [comment]
for now I've commented out all references to redis in `.platform/services.yaml` and `.platform.app.yaml`

**Comment by Crell** [comment]
This was caused by accidentally adding the `redis` extension back to the extension list.  No further work needed.
